dic = ['Hey, I know things look rough, but remember, every cloud has a silver lining. Except the cloud that stole my sandwich last week. That one was just rude. Cheer up, laughter is a great medicine!',
 "I understand you're going through a tough time, but remember, this too shall pass. Life is full of ups and downs, and this is just a stepping stone to something better. Keep your head up!",
 "It's okay to feel sad and angry. These are valid emotions. Let's take a moment to acknowledge them, and then think about practical steps we can take to address what's bothering you.",
 'In the grand scheme of life, these moments of hardship are what shape us. They are opportunities for growth and learning. Reflect on this experience and seek the wisdom it offers.',
 "I'm here for you. It's completely okay to feel this way. If you need to talk, or if there's anything I can do to make you feel better, just let me know. You're not alone.",
 "You've got this! You're stronger than you think, and I believe in you. Channel this energy into something positive. Let's turn these feelings into a force for good!",
 "Tell me everything. I'm here to listen, not to judge. Sometimes, just talking things out can make a big difference. I'm all ears for you.",
 "Let's shake things up a bit! How about we go on a little adventure or try something new? Sometimes, a change of scenery can really help clear the mind.",
 "I can sense how hard this is for you, and I deeply understand. It's okay to feel these emotions. Let's sit with them together, and when you're ready, we'll move forward.",
 "Let's break down what's making you feel this way and see if we can find a solution together. There's always a way to tackle a problem, step by step.",
 "Let's express these feelings through art. Painting, music, or writing can be a great outlet for your emotions.",
 "Remember, history is full of instances where people overcame great challenges. You're part of that grand narrative of resilience.",
 "Let's analyze the facts of the situation. Understanding the 'why' behind your feelings can sometimes help manage them.",
 'How about we spend some time in nature? Gardening or just being outdoors can be very therapeutic.',
 "Cooking can be a great way to relax. Let's make your favorite dish together, and enjoy the process of creation.",
 "A bit of physical activity might help. Let's go for a run, or play a sport. It's amazing how much exercise can boost your mood.",
 "I've been where you are, and I made it through. Let's talk about strategies that helped me when I felt this way.",
 "Sometimes, looking at the bigger picture of the universe helps put our problems in perspective. Let's meditate or do some yoga.",
 "Let's channel these feelings into action. Is there a cause you're passionate about that we can get involved in?",
 "When life throws you lemons, learn to juggle! Let's try to find balance, even when things are tough."]
