/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Clownfish.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Clownfish.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Clownfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Clownfish_1" geometry={nodes.Clownfish_1.geometry} material={materials.Clownfish_Main} skeleton={nodes.Clownfish_1.skeleton} />
            <skinnedMesh name="Clownfish_2" geometry={nodes.Clownfish_2.geometry} material={materials.Clownfish_Dark} skeleton={nodes.Clownfish_2.skeleton} />
            <skinnedMesh name="Clownfish_3" geometry={nodes.Clownfish_3.geometry} material={materials.Eyes} skeleton={nodes.Clownfish_3.skeleton} />
            <skinnedMesh name="Clownfish_4" geometry={nodes.Clownfish_4.geometry} material={materials.Clownfish_Light} skeleton={nodes.Clownfish_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Clownfish.glb')
