/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Koi.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Koi.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Koi" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Koi_1" geometry={nodes.Koi_1.geometry} material={materials.Eyes} skeleton={nodes.Koi_1.skeleton} />
            <skinnedMesh name="Koi_2" geometry={nodes.Koi_2.geometry} material={materials.Koi_Main} skeleton={nodes.Koi_2.skeleton} />
            <skinnedMesh name="Koi_3" geometry={nodes.Koi_3.geometry} material={materials.Koi_Fins} skeleton={nodes.Koi_3.skeleton} />
            <skinnedMesh name="Koi_4" geometry={nodes.Koi_4.geometry} material={materials.Koi_Light} skeleton={nodes.Koi_4.skeleton} />
            <skinnedMesh name="Koi_5" geometry={nodes.Koi_5.geometry} material={materials.Koi_Dark} skeleton={nodes.Koi_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Koi.glb')
