/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Puffer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Puffer.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Pufferfish001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Pufferfish002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Pufferfish002_1" geometry={nodes.Pufferfish002_1.geometry} material={materials.Pufferfish_Main} skeleton={nodes.Pufferfish002_1.skeleton} />
            <skinnedMesh name="Pufferfish002_2" geometry={nodes.Pufferfish002_2.geometry} material={materials.Pufferfish_Light} skeleton={nodes.Pufferfish002_2.skeleton} />
          </group>
          <group name="Pufferfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Pufferfish_1" geometry={nodes.Pufferfish_1.geometry} material={materials.Pufferfish_Main} skeleton={nodes.Pufferfish_1.skeleton} />
            <skinnedMesh name="Pufferfish_2" geometry={nodes.Pufferfish_2.geometry} material={materials.Pufferfish_Light} skeleton={nodes.Pufferfish_2.skeleton} />
            <skinnedMesh name="Pufferfish_3" geometry={nodes.Pufferfish_3.geometry} material={materials.Puffefish_Black} skeleton={nodes.Pufferfish_3.skeleton} />
            <skinnedMesh name="Pufferfish_4" geometry={nodes.Pufferfish_4.geometry} material={materials.Eyes} skeleton={nodes.Pufferfish_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Puffer.glb')
