/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Red Snapper.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Red Snapper.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="RedSnapper" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="RedSnapper_1" geometry={nodes.RedSnapper_1.geometry} material={materials.RedSnapper_Fins} skeleton={nodes.RedSnapper_1.skeleton} />
            <skinnedMesh name="RedSnapper_2" geometry={nodes.RedSnapper_2.geometry} material={materials.Eyes} skeleton={nodes.RedSnapper_2.skeleton} />
            <skinnedMesh name="RedSnapper_3" geometry={nodes.RedSnapper_3.geometry} material={materials.RedSnapper_Main} skeleton={nodes.RedSnapper_3.skeleton} />
            <skinnedMesh name="RedSnapper_4" geometry={nodes.RedSnapper_4.geometry} material={materials.RedSnapper_Light} skeleton={nodes.RedSnapper_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Red Snapper.glb')
