/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 Swordfish.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Swordfish.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Fish_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Main1} />
          </group>
          <group name="Swordfish" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Swordfish_1" geometry={nodes.Swordfish_1.geometry} material={materials.Swordfish_Light} skeleton={nodes.Swordfish_1.skeleton} />
            <skinnedMesh name="Swordfish_2" geometry={nodes.Swordfish_2.geometry} material={materials.Swordfish_Main} skeleton={nodes.Swordfish_2.skeleton} />
            <skinnedMesh name="Swordfish_3" geometry={nodes.Swordfish_3.geometry} material={materials.Swordfish_Dark} skeleton={nodes.Swordfish_3.skeleton} />
            <skinnedMesh name="Swordfish_4" geometry={nodes.Swordfish_4.geometry} material={materials.Eyes} skeleton={nodes.Swordfish_4.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Swordfish.glb')
